# Generated by Django 5.1.2 on 2024-10-25 19:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_type', models.CharField(choices=[('markdown', 'Markdown'), ('python', 'Python')], max_length=10)),
                ('answer', models.TextField()),
                ('created', models.DateTimeField(auto_now=True)),
                ('edit', models.DateTimeField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_number', models.IntegerField()),
                ('highlight_text', models.TextField()),
                ('exercise_text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Textbook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.BinaryField()),
            ],
        ),
        migrations.CreateModel(
            name='AnswerFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.TextField()),
                ('created', models.DateTimeField(auto_now=True)),
                ('edit', models.DateTimeField(default=None)),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='learning.answer')),
            ],
        ),
        migrations.AddField(
            model_name='answer',
            name='exercise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='learning.exercise'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='textbook',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='learning.textbook'),
        ),
    ]
