# Generated by Django 5.1.2 on 2024-10-25 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AnswerFeedback',
            new_name='Feedback',
        ),
    ]
